filesets:
  default:
    include:
      - ".watchcode.yaml"
      - "*.nim"
      - "nim.cfg"
    exclude:
    match_mode: "fnmatch"
    exclude_gitignore: true

tasks:
  frontend:
    fileset: default
    commands:
      - "npm run build_renderer"
    clear_screen: true
    queue_events: false

  run:
    fileset: default
    commands:
      - "npm start"
    clear_screen: true
    queue_events: false

  test:
    fileset: default
    commands:
      - "nim -r js -d:nodejs -d:testVanilla tests/tests.nim"
    clear_screen: true
    queue_events: false

default_task: frontend
#default_task: run
#default_task: test
log: false
sound: true
notifications: true
