filesets:
  default:
    include:
      - ".watchcode.yaml"
      - "*.nim"
      - "nim.cfg"
    exclude:
    match_mode: "fnmatch"
    exclude_gitignore: true

tasks:
  frontend:
    commands:
      - "npm run build_renderer"
    clear_screen: true
    queue_events: false

  run:
    commands:
      - "npm start"
    clear_screen: true
    queue_events: false

  test:
    commands:
      - "nim -r js -d:nodejs -d:testVanilla tests/tests.nim"
    clear_screen: true
    queue_events: false


targets:
  frontend:
    fileset: default
    task: frontend

  run:
    fileset: default
    task: run

  test:
    fileset: default
    task: test

#default_target: frontend
default_target: run
#default_target: test
log: false